---
- name: Update cloudflared on all servers
  hosts: all
  become: yes
  vars_files:
    - ../values.yaml
  tasks:
    - name: Download the latest cloudflared Linux package.
      shell: curl --location --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
    - name: Restart cloudflared service
      systemd:
        name: cloudflared
        state: restarted
        enabled: true
        masked: no