apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-hello
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: nginx
  source:
    repoURL: https://github.com/corvad/infra
    path: k3s-cluster/nginx-demo-hello
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
