# Projects are managed inline in this file for simplicity
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: ArgoCD Project
  sourceRepos:
    - "https://argoproj.github.io/argo-helm"
    - "https://github.com/corvad/infra"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudflared
  namespace: argocd
spec:
  description: Cloudflared Project
  sourceRepos:
    - "https://emberstack.github.io/helm-charts"
  destinations:
    - namespace: cloudflared
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx
  namespace: argocd
spec:
  description: Nginx Project
  sourceRepos:
    - "https://helm.nginx.com/stable"
    - "https://github.com/corvad/infra"
  destinations:
    - namespace: nginx
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
