apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: traefik
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v38.0.1
    helm:
      releaseName: traefik
      values: |
        .TrustedIPs: &TrustedIPs
          - 127.0.0.1/32
          - 10.0.0.0/8
        logs:
          general:
            level: TRACE
          access:
            enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
            forwardedHeaders:
              trustedIPs: *TrustedIPs
            proxyProtocol:
              trustedIPs: *TrustedIPs
          websecure:
            forwardedHeaders:
              trustedIPs: *TrustedIPs
            proxyProtocol:
              trustedIPs: *TrustedIPs
        deployment:
          replicas: 1
        service:
          enabled: true
          type: LoadBalancer
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true