apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-hello
  namespace: nginx
  labels:
    app: nginx-demo-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-hello
  template:
    metadata:
      labels:
        app: nginx-demo-hello
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 8080
              name: http
