apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-hello
  namespace: nginx
  labels:
    app: nginx-demo-hello
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx-demo-hello
  template:
    metadata:
      labels:
        app: nginx-demo-hello
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
