apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-hello
  namespace: nginx
  labels:
    app: nginx-demo-hello
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nginx-demo-hello
