---
- name: Install argocd
  hosts: control_plane[0]
  become: yes
  tasks:
    - name: Add Helm repo for argocd
      ansible.builtin.shell:
        cmd: helm repo add argo https://argoproj.github.io/argo-helm --kubeconfig /etc/rancher/k3s/k3s.yaml
    - name: Update Helm repos
      ansible.builtin.shell:
        cmd: helm repo update --kubeconfig /etc/rancher/k3s/k3s.yaml
    - name: Install argocd via Helm
      ansible.builtin.shell:
        cmd: |
          helm install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set configs.params.server.insecure=true \
            --set redis-ha.enabled=true \
            --set controller.replicas=1 \
            --set server.replicas=2 \
            --set repoServer.replicas=2 \
            --kubeconfig /etc/rancher/k3s/k3s.yaml