---
- name: Configure Gerrit site
  hosts: gerrit
  become: yes
  vars_files:
    - ../../values.yaml
  tasks:
    - name: Install Java
      apt:
        name:
          - openjdk-25-jdk-headless
          - git
        state: present
        update_cache: yes

    - name: Create gerrit system user
      user:
        name: "gerrit"
        system: yes
        home: "/home/gerrit"
        shell: /bin/bash
        state: present

    - name: Ensure gerrit site directory
      file:
        path: "/home/gerrit/site"
        owner: "gerrit"
        group: "gerrit"
        mode: '0755'
        state: directory

    - name: Ensure gerrit site etc directory
      file:
        path: "/home/gerrit/site/etc"
        owner: "gerrit"
        group: "gerrit"
        mode: '0755'
        state: directory

    - name: Download Gerrit WAR file
      get_url:
        url: "https://gerrit-releases.storage.googleapis.com/gerrit-{{ gerrit_version }}.war"
        dest: "/home/gerrit/gerrit.war"
        owner: "gerrit"
        group: "gerrit"
        mode: '0644'
        force: true

    - name: Ensure gerrit.config
      ansible.builtin.template:
        src: gerrit.config.j2
        dest: /home/gerrit/site/etc/gerrit.config
        owner: gerrit
        group: gerrit
        mode: '0644'

    - name: Ensure gitiles.config
      ansible.builtin.template:
        src: gitiles.config.j2
        dest: /home/gerrit/site/etc/gitiles.config
        owner: gerrit
        group: gerrit
        mode: '0644'

    - name: Initialize Gerrit site
      command: "java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site --no-auto-start --install-all-plugins"
      become_user: "gerrit"

    - name: Create gerrit systemd service file
      copy:
        src: gerrit.service.j2
        dest: /etc/systemd/system/gerrit.service
        mode: '0644'

    - name: Enable and start gerrit service
      systemd:
        name: gerrit
        enabled: true
        state: started
        daemon_reload: yes