---
- name: Update Gerrit site
  hosts: gerrit
  become: yes
  vars:
    gerrit_version: 3.13.1
  tasks:

    - name: Download Gerrit WAR file
      get_url:
        url: "https://gerrit-releases.storage.googleapis.com/gerrit-{{ gerrit_version }}.war"
        dest: "/home/gerrit/gerrit.war"
        owner: "gerrit"
        group: "gerrit"
        mode: '0644'
        force: true

    - name: Initialize Gerrit site
      command: "java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site --no-auto-start --install-all-plugins"
      become_user: "gerrit"

    - name: Create gerrit systemd service file
      copy:
        src: gerrit.service
        dest: /etc/systemd/system/gerrit.service
        mode: '0644'

    - name: Enable and start gerrit service
      systemd:
        name: gerrit
        enabled: true
        state: started
        daemon_reload: yes