---
- name: Jenkins Install
  hosts: jenkins
  become: yes
  tasks:
    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
      #in the future use the 2026.key
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'
        force: true

    - name: Add Jenkins apt repository with signed-by
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Ensure jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes