apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: traefik
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v38.0.1
    helm:
      releaseName: traefik
      values: |
        logs:
          general:
            level: DEBUG
        ingressRoute:
          dashboard:
            enabled: false
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
            forwardedHeaders:
              trustedIPs: 10.0.0.0/24
            proxyProtocol:
              trustedIPs: 10.0.0.0/24
          websecure:
            forwardedHeaders:
              trustedIPs: 10.0.0.0/24
            proxyProtocol:
              trustedIPs: 10.0.0.0/24
        deployment:
          replicas: 3
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true